spring:
    datasource:
        url: jdbc:mysql://192.168.91.1/wechatdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: wechat
        password: Wechat,123
        driver-class-name: com.mysql.jdbc.Driver

    redis:
        host: localhost
        password:
        port: 6379

mybatis:
    mapperLocations: classpath:mapper/*.xml
    configuration:
        mapUnderscoreToCamelCase: true
        default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
server:
    ssl:
        key-store: classpath:keystore.jks
        key-store-password: 24733956131
        key-store-type: JKS
#配置文件的位置信息
login:
    url: https://coder.newlandfinance.com:9999/images/